"""create session tables

Revision ID: eb6a4400d80d
Revises: 
Create Date: 2026-08-11 23:48:23.257917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6a4400d80d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=16), nullable=False),
    sa.Column('event_name', sa.String(length=128), nullable=True),
    sa.Column('data_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'round', 'session_type', name='uq_session_identity')
    )
    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver', sa.String(length=8), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time_seconds', sa.Numeric(precision=7, scale=3, asdecimal=False), nullable=True),
    sa.Column('sector_1_seconds', sa.Numeric(precision=7, scale=3, asdecimal=False), nullable=True),
    sa.Column('sector_2_seconds', sa.Numeric(precision=7, scale=3, asdecimal=False), nullable=True),
    sa.Column('sector_3_seconds', sa.Numeric(precision=7, scale=3, asdecimal=False), nullable=True),
    sa.Column('compound', sa.String(length=16), nullable=True),
    sa.Column('tyre_life', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['race_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pit_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver', sa.String(length=8), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Numeric(precision=7, scale=3, asdecimal=False), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['race_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver', sa.String(length=8), nullable=False),
    sa.Column('stint_number', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(length=16), nullable=True),
    sa.Column('start_lap', sa.Integer(), nullable=False),
    sa.Column('end_lap', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['race_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stints')
    op.drop_table('pit_stops')
    op.drop_table('laps')
    op.drop_table('race_sessions')
    # ### end Alembic commands ###
