"""add track_status to laps

Revision ID: f8815c820c91
Revises: eb6a4400d80d
Create Date: 2026-08-12 20:43:41.168086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8815c820c91'
down_revision: Union[str, Sequence[str], None] = 'eb6a4400d80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laps', sa.Column('track_status', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laps', 'track_status')
    # ### end Alembic commands ###
