"""add driver info and country/total_laps to sessions

Revision ID: fb478cfe46ab
Revises: f8815c820c91
Create Date: 2026-08-17 21:59:41.791790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb478cfe46ab'
down_revision: Union[str, Sequence[str], None] = 'f8815c820c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['race_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('race_sessions', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('race_sessions', sa.Column('total_laps', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race_sessions', 'total_laps')
    op.drop_column('race_sessions', 'country')
    op.drop_table('drivers')
    # ### end Alembic commands ###
